# Generated by Django 5.0.2 on 2024-02-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=400)),
                ('studentId', models.CharField(max_length=300)),
                ('examdate', models.DateTimeField()),
                ('attended', models.BooleanField()),
                ('submitted', models.BooleanField()),
                ('signature', models.TextField(default='In prgress, comming soon', max_length=100)),
            ],
        ),
    ]
