# Generated by Django 4.1.6 on 2024-02-29 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_register_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='course_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'date__gte': datetime.datetime(2024, 2, 29, 4, 47, 12, 142170, tzinfo=datetime.timezone.utc)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.exam_details'),
        ),
    ]
